---
title: "Relations entre morphologie et stratégies de nage chez les poissons des Grands Lacs"
author: "Amal Abarou, Ide Tchuileng, Christelle Baseka"
format:
  pdf:
    documentclass: report
    toc: true
editor: visual
lang: fr
bibliography: references.bib
---

<!--# Un rapport est différent d'un carnet de notes. Il ne s'agit donc pas de faire du copier-coller d'un document vers l'autre. Un rapport de synthèse doit être compréhensible sans devoir lire le carnet de notes. Le rapport de synthèse doit être  rédigé avec un style et une présentation adéquats. -->

## Introduction

<!--% Rédigez l'introduction de ce rapport en 5-6 phrases.-->

La morphologie des poissons constitue un déterminant majeur de leur écologie de déplacement, influençant la performance de nage, l’efficacité énergétique, les interactions sociales ainsi que la capacité à franchir des obstacles physiques tels que des rapides ou des passes à poissons. Les traits morphologiques tels que la forme du corps, la profondeur relative, le rapport d’aspect de la nageoire caudale ou encore la taille des nageoires pectorales sont directement associés aux stratégies de nage, qu’elles soient axées sur la vitesse, l’endurance, la manœuvrabilité ou la stabilité dans la colonne d’eau. De même, certains traits comportementaux, tels que la tendance à former des bancs, constituent des réponses écologiques façonnées par le régime hydrodynamique, la prédation ou les modes d’alimentation.

Dans ce contexte, la base de données FishPass Sortable Attribute Database (Benoit et al., 2023) constitue une ressource pertinente, regroupant des informations morphologiques, physiologiques, comportementales et phénologiques pour un large ensemble d’espèces des Grands Lacs. Elle permet notamment d’analyser les facteurs influençant la capacité des poissons à se déplacer et à franchir des aménagements anthropiques.

Pour ce projet, nous avons combiné deux ensembles de données issus de cette base : FishPass Morphology et FishPass Behaviour. L’objectif est d’étudier les relations entre traits morphologiques et comportements de nage, en particulier la tendance à former des bancs et la position verticale dans la colonne d’eau. Les variables retenues incluent des indicateurs de forme corporelle (profondeur du corps, rapport d’aspect, étroitesse du pédoncule caudal) ainsi que des traits fonctionnels liés à la nage (position et taille des nageoires, position et taille de l’œil).

Cette étude vise à déterminer si certains profils morphologiques sont associés à des stratégies de déplacement collectives ou individuelles, et dans quelle mesure la morphologie peut prédire le comportement. Une meilleure compréhension de ces relations éclaire les mécanismes sous-jacents à l’adaptation écologique et peut guider l’aménagement de dispositifs favorisant la migration des poissons dans les systèmes fluviaux aménagés.

## But

<!--% Rédigez le but de ce rapport en 2 phrases.-->

L’objectif de cette étude est d’examiner comment les traits morphologiques des poissons sont associés à la forme du corps, à la position verticale dans la colonne d’eau et au comportement de banc, et de déterminer dans quelle mesure la morphologie peut prédire ces stratégies de nage.

## Matériel et méthodes

<!--% Cette section doit comprendre deux parties. La première partie doit expliciter les données employées et la seconde traiter des analyses réalisées et des logiciels employés.-->

**Matériel :**

Le jeu de données utilisé provient de la base FishPass Sortable Attribute Database, rassemblée par Benoit *et al.* (2023). Cette base regroupe des informations morphologiques, physiologiques, comportementales et phénologiques pour les poissons des Grands Lacs.\
Dans ce projet, nous avons plus spécifiquement exploité les fichiers FishPass_Morphology_Database.csv et FishPass_Behaviour_Database.csv.

La base combinée couvre 220 espèces, réparties initialement sur 21 ordres taxonomiques et comprenant 21 variables biologiques. Afin d’étudier le lien entre morphologie et stratégies de nage, nous nous sommes concentrés sur un ensemble restreint mais pertinent de variables morphologiques et comportementales.

### Variables quantitatives retenues (8) :

-   Longueur maximale (cm) : taille maximale observée de l’espèce.

-   Profondeur du corps (% TL) : rapport entre la profondeur maximale et la longueur totale du corps.

-   Rapport d’aspect : indicateur de la forme et de la performance de la nageoire caudale.

-   Étroitesse du pédoncule caudal : finesse de la jonction entre le corps et la nageoire caudale.

-   Position verticale de la nageoire pectorale

-   Taille de la nageoire pectorale

-   Position verticale de l’œil

-   Taille de l’œil (% HL) : diamètre de l’œil rapporté à la longueur de la tête.

### Variables qualitatives retenues (4) :

-   Ordre : classification taxonomique de l’espèce.

-   Forme du corps : fusiform, elongated et short/deep.

-   Comportement de banc : schooling et non-schooling.

-   Position verticale dans la colonne d'eau : benthopelagic, dermesal et pelagic

#### Méthodes

-   **Fusion des données** : Les bases Morphology et Behaviour ont été combinées par espèce en utilisant les clés: `Order`, `Family`, `Genus`, `Scientific.Name` et `Common.Name`.

-   **Nettoyage** : renommage des colonnes en français, conversion des variables numériques, suppression des lignes avec valeurs manquantes, conversion en `factor` pour les variables qualitatives et ajout de labels et unités.

-   **Filtrage des ordres** : afin d’assurer une représentativité statistique suffisante, seuls les ordres présentant un effectif ≥ 10 individus ont été conservés. Les ordres retenus pour les analyses sont *Cypriniformes, Perciformes et Salmoniformes.* Les autres ordres ont été exclus pour éviter les biais liés aux faibles tailles d’échantillon.

    **Traitement des données :**

    **Logiciel :** Les analyses statistiques sont réalisées dans `r R.version.string` et plus précisément avec `{tidyverse}` version `r packageVersion("tidyverse")`, `{tabularise}` version `r packageVersion("tabularise")` et `{labelled}` version `r packageVersion("labelled")` sous `r osVersion`. Le seuil α est fixé à 5 %.

## Résultats

<!--% Présentez les deux modèles les plus pertinents que vous avez sélectionnés. Structurez la section en deux parties avec deux titres de niveau trois.-->

## Discussion et Conclusion

<!--% En tenant compte du but de votre carnet de notes et de vos résultats, discutez de résultats et proposez des conclusions à votre analyse en 5 à 10 phrases. -->

## Bibliographie

Benoit, D., Zielinski, D. P., Swanson, R. A., McLaughlin, R. L., Castro-Santos, T., Goodwin, A. E., Pratt, T. C., & Muir, A. M. (2023). *FishPass Sortable Attribute Database* (Version 1) \[Data set\]. Dryad. <https://doi.org/10.5061/dryad.fqz612jwj>
